name: Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    # llvm 12 requires glibc 2.33
    container: ubuntu:impish
    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install -y xz-utils libc6-dev curl build-essential

      - uses: actions/checkout@v2

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "12.0.1"

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
